version: '3.8'

services:

  react-app-0:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo-react-app-0
    networks:
      - app-network

  mongo-react-app-0:
    image: mongo:latest
    container_name: mongo-react-app-0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge