version: '3.8'

services:

  frontend:
    container_name: frontend
    build:
      context: ./front_end
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./front_end/.env
    networks:
      - employee-system-network

  backend:
    container_name: backend
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./back_end/.env
    depends_on:
      - mongo-employee-system
    networks:
      - employee-system-network

  mongo-employee-system:
    image: mongo:latest
    container_name: mongo-employee-system
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - employee-system-network

volumes:
  mongo-data:

networks:
  employee-system-network:
    name: employee-system-network
    driver: bridge
